import { db } from "@/lib/db";
import { leadHref } from "@/lib/crm/surface";
import type { Brand } from "@/lib/pipeline-engine/constants";
import { cairoDatesBack, cairoDayWindowFor, startOfCairoDay, utcToCairo } from "@/lib/datetime";
import { leadScopeWhere, type TodoScope } from "@/lib/services/todo";

/* ============================================================================
   ADR-081 — THE DAILY REPORT.

   Founder, verbatim: "I want to add a feature inside the system called the daily
   report. The daily report could be generated by the user himself — not the
   admin, not anyone — the user himself generates a daily report. A daily report
   goes through the following: how many leads did he take action on, even if this
   action was didn't answer, or move through the CRM, or a comment on any lead —
   and which leads had these changes. This report should be dynamic, so when I
   click on the lead I go to the lead. And this report should be day by day. I
   don't need this report to be kept... I just need to look back in history just
   three days... Also it should have a display on the number: how many leads did
   you interact with this day, and what interactions were those."

   FOUR PROPERTIES, EACH ONE OF HIS SENTENCES.

   1. IT IS HIS OWN REPORT. `actorId = the signed-in user` is the whole
      predicate, and there is no parameter anywhere in this module that could
      widen it: no userId on a wire, no team view, no admin variant. An admin
      opening the page reads HIS OWN actions. "Not the admin, not anyone."

   2. NOTHING IS KEPT. No table, no snapshot, no generate-and-save — "I don't
      need this report to be kept." It is computed from what the system already
      records, exactly the way the To-Do is (ADR-041), and "generate" in his
      words means "pull it up and look at it". `now` is injectable so a test can
      name the day, which is the only concession to testability the To-Do needed
      either.

   3. THREE CAIRO DAYS, AND NO FOURTH. "I don't want to know the last month,
      just the last three days." The window is built from Cairo DATE STRINGS
      (`cairoDatesBack`), never by subtracting hours from an instant: Egypt has a
      23-hour day and a 25-hour day every year and a fixed 86_400_000 lands on
      the wrong day on both of them. `DAILY_REPORT_DAYS` is the one literal, so
      widening it later is one number rather than a rewrite — while the ADR
      records that three is his instruction.

   4. THE COUNT IS THE FEATURE, AND IT COUNTS LEADS. He asked for the number
      twice. `leadCount` is DISTINCT LEADS: a lead he touched five times is ONE
      lead in the count and ONE row in the list, carrying its five interactions.
      `interactionCount` is the other number, kept separate so neither can be
      mistaken for the other.

   ---------------------------------------------------------------------------
   WHAT COUNTS AS AN INTERACTION: every row this product writes against a LEAD.

   His three examples are examples, not the list ("even if this action was..."),
   so the predicate is `entityType: "lead"` rather than a hand-written list of
   triggers — which is also what keeps a §10 row added next month inside the
   report by construction. That covers: the lead being added (create / PP-5),
   ready-to-close (B-RTC), the didn't-answer tally and its clear, archive and
   unarchive, an owner assignment, a delete, a field edit, every stage move and
   automatic transfer and same-stage record, a comment, a WhatsApp mark, a
   proposal corrected in place, the per-lead rows written when an owner's account
   is deleted, and an undo.

   DELIBERATELY OUTSIDE IT, named so the scope is a decision and not an
   oversight: the POST-WIN MONEY ADMIN. A milestone tick, a statement paid, a
   payment proof and a client edit log against `won_deal` / `statement` /
   `client`, not against the lead. The WIN ITSELF IS NOT LOST — the same
   transaction always writes the lead's own move row — only the money work that
   follows it is outside. Filtering on `entityType: "lead"` is also what stops
   the win being counted twice, since the `won_deal` row is a SIBLING of the
   lead row rather than a substitute for it. The partner/agent funnel
   (`partner_prospect`) is out too, inheriting ADR-061's removal of it from the
   To-Do: his word was "leads".

   AND THE TWO LEAD-SCOPED WRITES THAT KEEP NO LOG ROW, named here because the
   inventory above claims to be complete (review, Run 097). Both sit behind
   `requireLeadAccess`; neither touches `ActivityLog`, so neither can reach this
   projection whatever it filters on:

     · TICKING A TO-DO TASK DONE (`todo-done.ts`) writes one `TodoDone` row. The
       mark is keyed to the RECORD rather than to a lead (ADR-062), it means "this
       task is handled" and the To-Do's own Done section already shows it with the
       same attribution, and UNCHECKING DELETES IT — rewritable state, which a
       report about what happened must not be built on. The consequence is stated
       rather than hidden: a rep who ticks his due follow-ups and records nothing
       else reads a zero for the day. Founder item 5 on ADR-081.
     · SETTING A MEETING'S "ALSO BLOCKS" ATTENDEES (`meeting-attendees.ts`) writes
       `MeetingAttendee` rows. ADR-071 built it as a statement about whose TIME a
       meeting occupies, not about the lead. Same founder item.

   Making either countable means writing a NEW kind of log row against the lead —
   a new `LOG_ACTIONS` verb and new lines on every lead's History timeline — which
   is his call, not a detail of this screen.

   ONE TABLE, ONE PASS. Comments already write an ActivityLog row inside the
   same transaction as the comment, so reading `LeadComment` as a second source
   would double every comment. Two stage-move rows in one transaction (the
   automatic no-answer clear beside the move) are two INTERACTION LINES on one
   lead — never two leads.
   ========================================================================== */

/** His three days: today and the two before it. The only place the 3 is written
    (see property 3 above). */
export const DAILY_REPORT_DAYS = 3;

/** How far the viewer's own scope reaches — deliberately the To-Do's type and
    the To-Do's predicate (`leadScopeWhere`), not a second wall that could drift
    from `requireLeadAccess`. */
export type ReportScope = TodoScope;

/** One company this account HOLDS, with the scope it holds it under. The PAGE
    builds this from `companiesFor(user.roles)` + `bsRoleOrNull`, so permissions
    are resolved where the session is and this module never decides them. */
export interface ReportCompany {
  brand: Brand;
  scope: ReportScope;
}

/** Why a row carries no name and no link. `null` is the ordinary case. */
export type ReportRedaction =
  /** the lead was deleted — its log rows outlive it (ActivityLog has no FK) */
  | "deleted"
  /** it exists but is outside this viewer's scope today (reassigned, or moved
      out of the internal bucket) */
  | "out_of_scope";

export interface ReportInteraction {
  /** the ActivityLog row id */
  id: string;
  at: Date;
  action: string;
  trigger: string;
  fromStage: string | null;
  toStage: string | null;
  /** the stored actor label, which carries "(via …)" when an admin was acting as
      this person (see the impersonation note below) */
  actorLabel: string;
}

export interface ReportLeadRow {
  leadId: string;
  /** null when redacted — a row he may not be shown the name of */
  name: string | null;
  /** null when redacted. Never hand-built: `leadHref` is the one table that gets
      `?company=` right per brand (ADR-074). */
  href: string | null;
  /** null when redacted: the company of a lead outside this viewer's scope is
      itself a byte he does not hold */
  brand: Brand | null;
  archived: boolean;
  redacted: ReportRedaction | null;
  /** newest first */
  interactions: ReportInteraction[];
}

export interface ReportDay {
  /** Cairo calendar date, "YYYY-MM-DD" */
  date: string;
  isToday: boolean;
  /** THE HEADLINE — distinct leads touched on this Cairo day */
  leadCount: number;
  /** the other number: how many things he did to them */
  interactionCount: number;
  leads: ReportLeadRow[];
}

export interface DailyReport {
  /** always exactly DAILY_REPORT_DAYS entries, newest first — an empty day is a
      calm explicit zero, never an omitted section (founder: the report is
      "day by day", and a missing day reads as broken) */
  days: ReportDay[];
}

/** Is this stored actor label an IMPERSONATION label — "Omar Agent (via Elmur)"?

    The report shows the label only when this is true, and deliberately NOT when
    the label merely differs from the reader's current name. `actorLabel` is
    denormalised history, written once and never rewritten (users.ts says so in as
    many words: "deleting the actor must not rewrite what happened"), while an
    admin may rename an account at any time — so after one rename every row the
    person wrote before it carries his old name, and a bare string mismatch would
    print all of them in the "somebody else did this" slot. The rows are already
    filtered to `actorId = me`, so a second party can only ever be an impersonator,
    and this suffix is the only trace of one. Review, Run 097. */
export function isViaLabel(actorLabel: string): boolean {
  return /\(via .+\)$/.test(actorLabel.trim());
}

/* A redacted row is BUILT, never stripped — ADR-071's `busyMeeting` pattern. A
   field that has to be REMOVED is a field that survives the day somebody adds a
   new call site; a field that is never set cannot. The row still COUNTS: it was
   his action, and dropping it would silently shrink the headline number he asked
   for twice. */
function redactedLeadRow(
  leadId: string,
  redaction: ReportRedaction,
  interactions: ReportInteraction[],
): ReportLeadRow {
  return {
    leadId,
    name: null,
    href: null,
    brand: null,
    archived: false,
    redacted: redaction,
    interactions,
  };
}

/** THE REPORT — one person's own last three Cairo days.

    `primary` decides which company's rows sort first inside a day. It is the
    company the reader is switched to (ADR-067): the report spans every company
    the account holds — it is a report about a PERSON'S DAY, not about one
    pipeline (ADR-071: "the company decides WHOSE entries you are shown, never
    whose time is real") — so the switch reorders rather than filters, and every
    row wears its own company chip so two companies' leads can never be
    confused.

    IMPERSONATION attributes to the IMPERSONATED user: under impersonation
    `session.user.id` is theirs, so an admin acting as Omar fills OMAR's report.
    That is the honest reading of "what happened on this lead".

    WHAT THE REPORT CAN AND CANNOT SAY ABOUT THAT, stated exactly (review, Run
    097 corrected an overclaim here): the `(via …)` suffix is built in ONE writer
    in this product — `addLeadComment` (comments.ts), fed by leadComments.ts from
    `user.impersonatorId` — so it is the LEAD CHAT, and only the lead chat, whose
    lines can name the admin who typed them. Every other lead writer stamps
    `label: user.name`, which under impersonation is the impersonated person's own
    name, so a stage move or a didn't-answer made while acting as Omar is
    indistinguishable in this table from Omar's own. Marking those would mean
    threading the impersonator through every lead write path — a change to stored
    history across the whole product, not to this screen — and it is flagged for
    the founder rather than guessed at here. The report therefore surfaces the
    marker it really has (`isViaLabel`) and claims nothing beyond it. */
export async function dailyReportFor(opts: {
  /** the SIGNED-IN user, taken from the session by the page — never from a
      query parameter, because there is no report but your own */
  actorId: string;
  companies: ReportCompany[];
  primary?: Brand;
  now?: Date;
  days?: number;
}): Promise<DailyReport> {
  const now = opts.now ?? new Date();
  const dayCount = opts.days ?? DAILY_REPORT_DAYS;
  const dates = cairoDatesBack(now, dayCount); // newest first
  const oldest = dates[dates.length - 1]!;
  const from = startOfCairoDay(oldest);
  const to = cairoDayWindowFor(dates[0]!).end;

  /* ONE query for the whole window — never one per day, and never one per lead.
     Served by ActivityLog_actorId_createdAt_idx (ADR-081's migration): without
     it this is a Seq Scan over the product's busiest table on every page open. */
  const rows = await db.activityLog.findMany({
    where: {
      actorId: opts.actorId,
      entityType: "lead",
      createdAt: { gte: from, lt: to },
    },
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      entityId: true,
      action: true,
      trigger: true,
      fromStage: true,
      toStage: true,
      createdAt: true,
      actorLabel: true,
    },
  });

  /* Bucket by the row's CAIRO date — read off the instant itself, never compared
     against boundary instants, which is DST-safe by construction. Then group by
     lead inside the day: rows arrive newest-first, so each lead's interaction
     list is newest-first and its FIRST row is its latest. */
  const byDate = new Map<string, Map<string, ReportInteraction[]>>();
  for (const date of dates) byDate.set(date, new Map());
  for (const row of rows) {
    const bucket = byDate.get(utcToCairo(row.createdAt).date);
    if (!bucket) continue; // outside the three days (cannot happen; cheap to keep honest)
    const list = bucket.get(row.entityId) ?? [];
    list.push({
      id: row.id,
      at: row.createdAt,
      action: row.action,
      trigger: row.trigger,
      fromStage: row.fromStage,
      toStage: row.toStage,
      actorLabel: row.actorLabel,
    });
    bucket.set(row.entityId, list);
  }

  /* ONE scoped lookup over the union of every day's ids. SCOPED, not
     fetched-then-filtered-in-the-view: the wall is the query, and it is the
     To-Do's own predicate (leadScopeWhere) per company the account holds.
     ARCHIVED leads are deliberately NOT excluded — their detail page renders
     read-only with an Archived badge, and a lead he worked and then archived is
     still work he did that day. */
  const ids = [...new Set(rows.map((r) => r.entityId))];
  const visible = new Map<string, { name: string; brand: Brand; archived: boolean }>();
  if (ids.length > 0 && opts.companies.length > 0) {
    const leads = await db.lead.findMany({
      where: {
        id: { in: ids },
        OR: opts.companies.map((c) => leadScopeWhere(c.brand, c.scope)),
      },
      select: { id: true, name: true, brand: true, archived: true },
    });
    for (const lead of leads) {
      visible.set(lead.id, {
        name: lead.name,
        brand: lead.brand as Brand,
        archived: lead.archived,
      });
    }
  }

  /* The ids that did not come back are DELETED or OUT OF SCOPE, and the two need
     different copy: "Deleted lead" is a fact about the record, "No longer one of
     your leads" is a fact about him. One id-only probe tells them apart. It
     reveals existence alone, about rows HE HIMSELF acted on — no name, no
     company, no owner — which is why it is a probe and not a second read. */
  const missing = ids.filter((id) => !visible.has(id));
  const stillExists = new Set<string>();
  if (missing.length > 0) {
    const probe = await db.lead.findMany({ where: { id: { in: missing } }, select: { id: true } });
    for (const p of probe) stillExists.add(p.id);
  }

  const today = dates[0]!;
  const days: ReportDay[] = dates.map((date) => {
    const bucket = byDate.get(date)!;
    const leads: ReportLeadRow[] = [];
    let interactionCount = 0;
    for (const [leadId, interactions] of bucket) {
      interactionCount += interactions.length;
      const lead = visible.get(leadId);
      leads.push(
        lead
          ? {
              leadId,
              name: lead.name,
              href: leadHref(lead.brand, leadId),
              brand: lead.brand,
              archived: lead.archived,
              redacted: null,
              interactions,
            }
          : redactedLeadRow(
              leadId,
              stillExists.has(leadId) ? "out_of_scope" : "deleted",
              interactions,
            ),
      );
    }
    /* the switched-to company first, then most recently touched first.

       A REDACTED row has no company to sort by, and it is ordered AS IF it were
       the company being looked at — so redaction changes what a row SAYS and
       never where in the day it appears. The alternative (nulls last) pushed
       every deleted or reassigned lead to the bottom of the day however recent
       it was, which reads as if the report had lost track of it; and ranking
       through this one function keeps the comparator a consistent total order,
       which a "reorder only when both brands are known" rule would not be. */
    const rank = (row: ReportLeadRow) =>
      !opts.primary || (row.brand ?? opts.primary) === opts.primary ? 0 : 1;
    const latest = (row: ReportLeadRow) => row.interactions[0]?.at.getTime() ?? 0;
    leads.sort((a, b) => rank(a) - rank(b) || latest(b) - latest(a));
    return {
      date,
      isToday: date === today,
      /* DISTINCT LEADS. Asserted directly in the suite as
         `leadCount === new Set(rows.map(r => r.entityId)).size` per day, because
         a headline number that counted ACTIONS would be wrong in exactly the way
         he pre-empted: "a lead touched five times is one lead". */
      leadCount: leads.length,
      interactionCount,
      leads,
    };
  });

  return { days };
}
