import { beforeEach, describe, expect, it } from "vitest";
import { readSheet } from "read-excel-file/node";
import readXlsxFile from "read-excel-file/node";
import { strFromU8, unzipSync } from "fflate";
import { db } from "@/lib/db";
import { resetDb } from "@/tests/db-reset";
import { utcToCairo } from "@/lib/datetime";
import { createLead } from "./leads";
import { buildLeadsWorkbook, LEAD_EXPORT_COLUMNS } from "./leads-export";
import type { Actor } from "./activity";

/* ============================================================================
   ADR-083 — THE FILE ITSELF, read back.

   The whole reason this is a real .xlsx and not a CSV is that Excel silently
   corrupts two things in a CSV, and both of them are the point of the sheet:

     · an Egyptian mobile loses its leading zero ("01012345678" → 1012345678),
       corrupting the single field he calls the lead on;
     · Arabic names mis-decode without a byte-order mark.

   A test that only asserted "a buffer came back" would prove neither. So every
   case here GENERATES THE REAL FILE and then PARSES IT BACK — with
   `read-excel-file`, a different library by the same author with its own XML
   reader, and for the two structural claims (is the phone really a text cell,
   is the sheet really right-to-left) by unzipping the archive and reading the
   SpreadsheetML the way Excel will.

   The fixtures are deliberately nasty: a leading zero, an Arabic name and an
   Arabic company, a lead in every one of the four statuses he named, a
   cross-company twin that must be ABSENT, a lead with no records at all, and a
   zero in the tally column.
   ========================================================================== */

const actor: Actor = { id: null, label: "Test Admin" };

let seq = 0;
function lead(
  brand: "bsystems" | "byteforce",
  name: string,
  extra?: { number?: string; companyName?: string; email?: string; position?: string; industry?: string },
) {
  seq += 1;
  return createLead(
    brand,
    {
      name,
      /* every number in this product starts with a zero — that is the fixture */
      number: extra?.number ?? `0100000${String(1000 + seq)}`,
      type: "cold_call",
      ...(extra?.companyName ? { companyName: extra.companyName } : {}),
      ...(extra?.email ? { email: extra.email } : {}),
      ...(extra?.position ? { position: extra.position } : {}),
      ...(extra?.industry ? { industry: extra.industry } : {}),
    },
    actor,
  );
}

/** The sheet as a grid of cells, straight out of the generated bytes. */
async function readBack(company: "bsystems" | "byteforce", locale: "en" | "ar" = "en") {
  const { buffer, filename, rows } = await buildLeadsWorkbook(company, locale);
  const grid = await readSheet(buffer);
  const sheets = await readXlsxFile(buffer);
  return { grid, filename, rows, buffer, sheetName: sheets[0]?.sheet };
}

/** An XLSX date is a FRACTION OF A DAY in a float, so a value like 14:00 is
    not exactly representable and a write-then-read costs under a millisecond
    (13:59:59.999 for 14:00). That is below anything a date format can show —
    Excel rounds a serial to the unit it is printing — so these assertions round
    to the minute too, which is the precision the cells are formatted at.
    Equality to the MINUTE is the claim; the day is asserted separately. */
function toMinute(d: Date): string {
  return new Date(Math.round(d.getTime() / 60_000) * 60_000).toISOString();
}

/** A column's index by its key, so a test never counts letters. */
function col(key: string): number {
  const i = LEAD_EXPORT_COLUMNS.findIndex((c) => c.key === key);
  if (i < 0) throw new Error(`no export column "${key}"`);
  return i;
}

/** The data row for a lead, found by name. */
function rowFor(grid: unknown[][], name: string): unknown[] {
  const row = grid.slice(1).find((r) => r[col("name")] === name);
  if (!row) throw new Error(`no row for "${name}" in the generated file`);
  return row;
}

beforeEach(async () => {
  await resetDb();
});

/* -------------------------------------------------------------------------- */

describe("the leading zero survives — the reason this is not a CSV", () => {
  it("comes back out of the real file as eleven characters, not a number", async () => {
    await lead("bsystems", "Zero Lead", { number: "01012345678" });

    const { grid } = await readBack("bsystems");
    const phone = rowFor(grid, "Zero Lead")[col("phone")];

    expect(typeof phone).toBe("string");
    expect(phone).toBe("01012345678");
    /* the failure mode spelled out: a CSV (or a numeric cell) gives this */
    expect(phone).not.toBe(1012345678);
    expect(String(phone).startsWith("0")).toBe(true);
    expect(String(phone)).toHaveLength(11);
  });

  it("the cell is a TEXT cell in the SpreadsheetML, not a formatted number", async () => {
    await lead("bsystems", "Zero Lead", { number: "01012345678" });
    const { buffer } = await readBack("bsystems");

    const zip = unzipSync(new Uint8Array(buffer));
    const sheet = strFromU8(zip["xl/worksheets/sheet1.xml"]!);
    const shared = strFromU8(zip["xl/sharedStrings.xml"]!);

    /* the number lives in sharedStrings — i.e. it is a string, and the zero is
       part of it — and the cell that points at it is typed `t="s"`. A numeric
       cell would carry <v>1012345678</v> with no type at all, and no amount of
       display formatting would put the zero back in the data. */
    expect(shared).toContain("<t>01012345678</t>");
    const index = shared.split("<si>").findIndex((si) => si.includes("<t>01012345678</t>")) - 1;
    expect(index).toBeGreaterThanOrEqual(0);
    expect(sheet).toContain(`t="s"><v>${index}</v>`);
    expect(sheet).not.toContain("<v>1012345678</v>");
  });

  it("a zero-prefixed number is preserved for EVERY lead in the file", async () => {
    for (let i = 0; i < 12; i++) {
      await lead("bsystems", `Lead ${i}`, { number: `0101234567${i}` });
    }
    const { grid } = await readBack("bsystems");
    const phones = grid.slice(1).map((r) => r[col("phone")]);
    expect(phones).toHaveLength(12);
    for (const p of phones) {
      expect(typeof p).toBe("string");
      expect(String(p).startsWith("0")).toBe(true);
    }
  });
});

/* -------------------------------------------------------------------------- */

describe("Arabic round-trips", () => {
  it("an Arabic name and company come back byte-for-byte", async () => {
    await lead("bsystems", "محمد عبد الرحمن", {
      companyName: "شركة النيل للتجارة",
      position: "مدير المشتريات",
      industry: "الإنشاءات",
    });

    const { grid } = await readBack("bsystems");
    const row = rowFor(grid, "محمد عبد الرحمن");
    expect(row[col("name")]).toBe("محمد عبد الرحمن");
    expect(row[col("company")]).toBe("شركة النيل للتجارة");
    expect(row[col("position")]).toBe("مدير المشتريات");
    expect(row[col("industry")]).toBe("الإنشاءات");
  });

  it("the HEADERS follow the viewer's language", async () => {
    await lead("bsystems", "Anybody");

    const en = await readBack("bsystems", "en");
    expect(en.grid[0]![col("name")]).toBe("Name");
    expect(en.grid[0]![col("status")]).toBe("Status");
    expect(en.sheetName).toBe("Leads");

    const ar = await readBack("bsystems", "ar");
    expect(ar.grid[0]![col("name")]).toBe("الاسم");
    expect(ar.grid[0]![col("status")]).toBe("الحالة");
    expect(ar.grid[0]![col("phone")]).toBe("الرقم");
    expect(ar.sheetName).toBe("العملاء المحتملون");
    /* and the English file is untouched by the Arabic one existing */
    expect(ar.grid[0]).not.toEqual(en.grid[0]);
  });

  it("an Arabic export sets the sheet RIGHT-TO-LEFT; an English one does not", async () => {
    await lead("bsystems", "Anybody");

    const sheetXml = async (locale: "en" | "ar") => {
      const { buffer } = await readBack("bsystems", locale);
      return strFromU8(unzipSync(new Uint8Array(buffer))["xl/worksheets/sheet1.xml"]!);
    };

    expect(await sheetXml("ar")).toContain('rightToLeft="1"');
    expect(await sheetXml("en")).not.toContain("rightToLeft");
  });

  it("the translated STAGE and TYPE labels are the ones the screens use", async () => {
    const l = await lead("bsystems", "Arabic Stage");
    await db.lead.update({ where: { id: l.id }, data: { stage: "negotiation" } });

    const { grid } = await readBack("bsystems", "ar");
    const row = rowFor(grid, "Arabic Stage");
    expect(row[col("stage")]).toBe("تفاوض"); // labels.ts's own stageMsgs
    expect(row[col("type")]).toBe("اتصال مباشر"); // cold_call
    expect(row[col("whatsapp")]).toBe("لا");
  });
});

/* -------------------------------------------------------------------------- */

describe("real typed cells — not a grid of strings", () => {
  it("dates come back as DATES, carrying the CAIRO day", async () => {
    const l = await lead("bsystems", "Dated Lead");
    /* 2026-10-05 23:30 UTC is 2026-10-06 01:30 in Cairo. A sheet that handed
       Prisma's Date straight to the cell would print the 5th while every screen
       in the product says the 6th — one day's disagreement, on the column he
       would sort by. */
    const created = new Date("2026-10-05T23:30:00.000Z");
    await db.lead.update({ where: { id: l.id }, data: { createdAt: created } });

    const { grid } = await readBack("bsystems");
    const cell = rowFor(grid, "Dated Lead")[col("created")];

    expect(cell).toBeInstanceOf(Date);
    expect(typeof cell).not.toBe("string");
    const asDate = cell as Date;
    /* the serial is the Cairo wall clock, so reading it back as UTC gives the
       Cairo hands — which is exactly what `formatCairo` prints on screen */
    expect(toMinute(asDate)).toBe("2026-10-06T02:30:00.000Z"); // Cairo is UTC+3 in October (DST)
    expect(utcToCairo(created).date).toBe("2026-10-06");
  });

  it("a follow-up with NO chosen time is a DATE cell with no clock on it", async () => {
    const l = await lead("bsystems", "Follow Lead");
    await db.followUp.create({
      data: {
        leadId: l.id,
        context: "initial",
        /* ADR-061's 09:00 Cairo default — a time nobody chose */
        dueAt: new Date("2026-11-10T07:00:00.000Z"),
        dueTimeSet: false,
        method: "call",
      },
    });

    const { grid, buffer } = await readBack("bsystems");
    const cell = rowFor(grid, "Follow Lead")[col("nextFollowUp")];
    expect(cell).toBeInstanceOf(Date);
    /* midnight Cairo — ADR-063's rule (never print a clock nobody chose), and
       it is what makes Excel's "equals 10/11/2026" filter match */
    expect(toMinute(cell as Date)).toBe("2026-11-10T00:00:00.000Z");

    const styles = strFromU8(unzipSync(new Uint8Array(buffer))["xl/styles.xml"]!);
    expect(styles).toContain('formatCode="dd/mm/yyyy"');
  });

  it("a follow-up with a CHOSEN time keeps its clock", async () => {
    const l = await lead("bsystems", "Timed Lead");
    await db.followUp.create({
      data: {
        leadId: l.id,
        context: "initial",
        dueAt: new Date("2026-11-10T14:45:00.000Z"), // 16:45 Cairo
        dueTimeSet: true,
        method: "call",
      },
    });

    const { grid } = await readBack("bsystems");
    const cell = rowFor(grid, "Timed Lead")[col("nextFollowUp")];
    expect(toMinute(cell as Date)).toBe("2026-11-10T16:45:00.000Z");
  });

  it("money is a NUMBER, in pounds, with a money format", async () => {
    const l = await lead("bsystems", "Valued Lead");
    await db.proposal.create({
      /* stored in piasters (ADR-018) — 1,500.50 EGP */
      data: { leadId: l.id, service: "Audit", estimatedValue: 150_050 },
    });

    const { grid, buffer } = await readBack("bsystems");
    const cell = rowFor(grid, "Valued Lead")[col("value")];
    expect(typeof cell).toBe("number");
    expect(cell).toBe(1500.5);
    /* not the minor units, and not a string with a currency glued on */
    expect(cell).not.toBe(150050);
    expect(cell).not.toBe("EGP 1,500.50");

    const styles = strFromU8(unzipSync(new Uint8Array(buffer))["xl/styles.xml"]!);
    expect(styles).toContain('formatCode="#,##0.00"');
  });

  it("a won lead with no proposal still carries its won value", async () => {
    const bf = await lead("byteforce", "Won Without Proposal");
    await db.lead.update({ where: { id: bf.id }, data: { stage: "won" } });
    await db.wonInfo.create({
      data: {
        leadId: bf.id,
        estimatedValue: 80_000_00,
        technicalOwner: "Nour",
        collectedAmount: 0,
      },
    });

    const { grid } = await readBack("byteforce");
    expect(rowFor(grid, "Won Without Proposal")[col("value")]).toBe(80_000);
  });

  it("the tally is a number — including the honest ZERO", async () => {
    const tried = await lead("bsystems", "Tried Thrice");
    await db.lead.update({
      where: { id: tried.id },
      data: { noAnswer: true, noAnswerCount: 3 },
    });
    await lead("bsystems", "Never Tried");

    const { grid } = await readBack("bsystems");
    expect(rowFor(grid, "Tried Thrice")[col("noAnswer")]).toBe(3);
    /* 0, not blank: the column has to sum and sort, which is what ADR-064's
       counter was asked for */
    expect(rowFor(grid, "Never Tried")[col("noAnswer")]).toBe(0);
  });

  it("every column of a bare lead is either a value or EMPTY — never the string \"null\"", async () => {
    await lead("bsystems", "Bare Lead");
    const { grid } = await readBack("bsystems");
    const row = rowFor(grid, "Bare Lead");
    expect(row).toHaveLength(LEAD_EXPORT_COLUMNS.length);
    for (const cell of row) {
      expect(cell).not.toBe("null");
      expect(cell).not.toBe("undefined");
      expect(cell).not.toBe("NaN");
    }
    /* the optional record columns are genuinely blank */
    expect(row[col("nextFollowUp")]).toBe(null);
    expect(row[col("latestMeeting")]).toBe(null);
    expect(row[col("value")]).toBe(null);
    expect(row[col("lostReason")]).toBe(null);
  });
});

/* -------------------------------------------------------------------------- */

describe("EVERY lead, ever — and the column that says which", () => {
  it("live, won, lost AND archived all appear, each with the right status", async () => {
    const live = await lead("bsystems", "Still Live");
    await db.lead.update({ where: { id: live.id }, data: { stage: "following_up" } });

    const won = await lead("bsystems", "Closed Won");
    await db.lead.update({ where: { id: won.id }, data: { stage: "won" } });

    const lost = await lead("bsystems", "Gone Cold");
    await db.lead.update({ where: { id: lost.id }, data: { stage: "lost" } });
    await db.lostInfo.create({ data: { leadId: lost.id, reason: "Chose a cheaper vendor" } });

    const archived = await lead("bsystems", "Put Away");
    await db.lead.update({
      where: { id: archived.id },
      data: { archived: true, archivedAt: new Date() },
    });

    const { grid, rows } = await readBack("bsystems");
    expect(rows).toBe(4);
    expect(grid).toHaveLength(5); // header + four

    expect(rowFor(grid, "Still Live")[col("status")]).toBe("Live");
    expect(rowFor(grid, "Closed Won")[col("status")]).toBe("Won");
    expect(rowFor(grid, "Gone Cold")[col("status")]).toBe("Lost");
    expect(rowFor(grid, "Put Away")[col("status")]).toBe("Archived");
    expect(rowFor(grid, "Gone Cold")[col("lostReason")]).toBe("Chose a cheaper vendor");
  });

  it("an ARCHIVED WON lead reads Archived in Status and Won in Stage", async () => {
    /* the overlap, decided in lib/crm/leads-export.ts: archived wins, because
       it is the answer to "where did this lead go" — and nothing is lost,
       because the Stage column beside it still counts the win */
    const l = await lead("bsystems", "Won Then Filed");
    await db.lead.update({
      where: { id: l.id },
      data: { stage: "won", archived: true, archivedAt: new Date() },
    });

    const { grid } = await readBack("bsystems");
    const row = rowFor(grid, "Won Then Filed");
    expect(row[col("status")]).toBe("Archived");
    expect(row[col("stage")]).toBe("Won");
  });

  it("the row count matches the DATABASE — archived included, filters irrelevant", async () => {
    for (let i = 0; i < 7; i++) await lead("bsystems", `Active ${i}`);
    for (let i = 0; i < 5; i++) {
      const l = await lead("bsystems", `Filed ${i}`);
      await db.lead.update({ where: { id: l.id }, data: { archived: true } });
    }
    /* and a handful of the other company's, which must not be in this file */
    for (let i = 0; i < 3; i++) await lead("byteforce", `Foreign ${i}`);

    const inDb = await db.lead.count({ where: { brand: "bsystems" } });
    expect(inDb).toBe(12);

    const { grid, rows } = await readBack("bsystems");
    expect(rows).toBe(inDb);
    expect(grid.slice(1)).toHaveLength(inDb);
    const names = grid.slice(1).map((r) => r[col("name")]);
    expect(names).toContain("Filed 0");
    expect(names.filter((n) => String(n).startsWith("Foreign"))).toEqual([]);
  });

  it("one company's file never contains the other's leads — in either direction", async () => {
    await lead("bsystems", "B-Systems Client");
    await lead("byteforce", "ByteForce Client");

    const bs = await readBack("bsystems");
    expect(bs.rows).toBe(1);
    expect(bs.grid[1]![col("name")]).toBe("B-Systems Client");

    const bf = await readBack("byteforce");
    expect(bf.rows).toBe(1);
    expect(bf.grid[1]![col("name")]).toBe("ByteForce Client");
  });

  it("an empty company still produces a valid file with its header row", async () => {
    const { grid, rows } = await readBack("byteforce");
    expect(rows).toBe(0);
    expect(grid).toHaveLength(1);
    expect(grid[0]).toHaveLength(LEAD_EXPORT_COLUMNS.length);
  });

  it("the rows are newest-added first — the Leads table's own default order", async () => {
    const a = await lead("bsystems", "Oldest");
    const b = await lead("bsystems", "Middle");
    const c = await lead("bsystems", "Newest");
    await db.lead.update({ where: { id: a.id }, data: { createdAt: new Date("2026-01-01T09:00:00Z") } });
    await db.lead.update({ where: { id: b.id }, data: { createdAt: new Date("2026-05-01T09:00:00Z") } });
    await db.lead.update({ where: { id: c.id }, data: { createdAt: new Date("2026-09-01T09:00:00Z") } });

    const { grid } = await readBack("bsystems");
    expect(grid.slice(1).map((r) => r[col("name")])).toEqual(["Newest", "Middle", "Oldest"]);
  });
});

/* -------------------------------------------------------------------------- */

describe("the people and the attributions", () => {
  it("owner, sales rep and the introducing partner each land in their column", async () => {
    const rep = await db.salesRep.create({ data: { brand: "bsystems", name: "Omar Sales" } });
    const owner = await db.user.create({
      data: { name: "Nourhan Agent", phone: "+201005550111", passwordHash: "x" },
    });
    const prospect = await db.partnerProspect.create({
      data: {
        name: "Hany",
        companyName: "Nile Partners",
        number: "0105550222",
        businessActivity: "Distribution",
        stage: "won",
        converted: true,
      },
    });
    const partner = await db.partner.create({
      data: {
        prospectId: prospect.id,
        companyName: "Nile Partners",
        keyPersonName: "Hany",
        keyPersonRole: "CEO",
        address: "1 Nile St",
        number: "0105550222",
        businessActivity: "Distribution",
        importance: "high",
      },
    });

    const l = await createLead(
      "bsystems",
      { name: "Attributed Lead", number: "01099988877", type: "campaign_lead" },
      actor,
      { attribution: { partnerId: partner.id }, ownerType: "agent", ownerUserId: owner.id },
    );
    await db.lead.update({ where: { id: l.id }, data: { salesRepId: rep.id } });

    const { grid } = await readBack("bsystems");
    const row = rowFor(grid, "Attributed Lead");
    expect(row[col("owner")]).toBe("Nourhan Agent");
    expect(row[col("salesRep")]).toBe("Omar Sales");
    expect(row[col("partner")]).toBe("Nile Partners");
    expect(row[col("ownerBucket")]).toBe("Agents");
    expect(row[col("type")]).toBe("Campaign lead");
  });

  it("the WhatsApp mark is a Yes/No, and it is the RECORD's", async () => {
    const sent = await lead("bsystems", "Messaged");
    await db.lead.update({
      where: { id: sent.id },
      data: { whatsappSentAt: new Date(), whatsappSentByLabel: "Elmur" },
    });
    await lead("bsystems", "Not Messaged");

    const { grid } = await readBack("bsystems");
    expect(rowFor(grid, "Messaged")[col("whatsapp")]).toBe("Yes");
    expect(rowFor(grid, "Not Messaged")[col("whatsapp")]).toBe("No");
  });

  it("the latest meeting is the one printed, and a slotless meeting is blank", async () => {
    const l = await lead("bsystems", "Met Twice");
    await db.meeting.create({
      data: { leadId: l.id, arranged: true, datetime: new Date("2026-03-01T10:00:00.000Z") },
    });
    await db.meeting.create({
      data: { leadId: l.id, arranged: true, datetime: new Date("2026-04-02T12:00:00.000Z") },
    });

    const unslotted = await lead("bsystems", "Needs A Slot");
    await db.meeting.create({ data: { leadId: unslotted.id, arranged: false } });

    const { grid } = await readBack("bsystems");
    const met = rowFor(grid, "Met Twice")[col("latestMeeting")] as Date;
    /* 12:00 UTC is 14:00 in Cairo (summer) — the cell is the Cairo clock */
    expect(met).toBeInstanceOf(Date);
    expect(toMinute(met)).toBe("2026-04-02T14:00:00.000Z");
    expect(rowFor(grid, "Needs A Slot")[col("latestMeeting")]).toBe(null);
  });
});

/* -------------------------------------------------------------------------- */

describe("the download itself", () => {
  it("is named for the company and the Cairo day, and the two cannot collide", async () => {
    await lead("bsystems", "Anybody");
    const today = utcToCairo(new Date()).date;
    const bs = await buildLeadsWorkbook("bsystems", "en");
    const bf = await buildLeadsWorkbook("byteforce", "en");
    expect(bs.filename).toBe(`b-systems-leads-${today}.xlsx`);
    expect(bf.filename).toBe(`byteforce-leads-${today}.xlsx`);
    expect(bs.filename).not.toBe(bf.filename);
  });

  it("is a real ZIP container with the parts Excel opens", async () => {
    await lead("bsystems", "Anybody");
    const { buffer } = await readBack("bsystems");
    /* "PK" — if this were a CSV with a different extension, Excel would still
       open it and silently eat the leading zeros, which is the bug */
    expect(buffer.subarray(0, 2).toString("latin1")).toBe("PK");
    const entries = Object.keys(unzipSync(new Uint8Array(buffer)));
    expect(entries).toContain("xl/worksheets/sheet1.xml");
    expect(entries).toContain("xl/styles.xml");
    expect(entries).toContain("xl/sharedStrings.xml");
    expect(entries).toContain("[Content_Types].xml");
  });

  it("the header row is frozen, so it survives ten thousand rows of scrolling", async () => {
    await lead("bsystems", "Anybody");
    const { buffer } = await readBack("bsystems");
    const sheet = strFromU8(unzipSync(new Uint8Array(buffer))["xl/worksheets/sheet1.xml"]!);
    expect(sheet).toContain('ySplit="1"');
    expect(sheet).toContain('state="frozen"');
  });

  it("has the twenty-one columns, each with a header and no duplicate key", async () => {
    const keys = LEAD_EXPORT_COLUMNS.map((c) => c.key);
    expect(keys).toHaveLength(21);
    expect(new Set(keys).size).toBe(21);
    for (const c of LEAD_EXPORT_COLUMNS) {
      expect(c.header.en.length, c.key).toBeGreaterThan(0);
      expect(c.header.ar.length, c.key).toBeGreaterThan(0);
      /* every header is translated — no Arabic column falls back to English */
      expect(c.header.ar, c.key).not.toBe(c.header.en);
      expect(c.width, c.key).toBeGreaterThan(0);
    }
  });
});
